pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = "spe-frontend"
        KUBERNETES_NAMESPACE = 'default'
        GITHUB_REPO_URL = 'https://github.com/abhisheksharma402/SPE-Major-Project.git'
     //    KUBECONFIG = credentials('kube-cred-main')
    }

    stages {
          stage('Checkout') {
               steps {
               
				script{
					git branch: 'React-server/main', url: "${GITHUB_REPO_URL}"
				}
			}
          }

          stage('Building Docker Image')
          {
               steps {

                    script {  
                         dir('SPE Major Project'){
                              docker.build("${DOCKER_IMAGE_NAME}", '.')
                         }
                    }

               }
          }

          stage('Pushing Docker Image')
		{
			steps {

				script {

					docker.withRegistry('', 'dockerhub-credentials') {

						sh "docker image tag spe-frontend abhisheksharma402/spe-frontend:version2.0"
						sh "docker push abhisheksharma402/spe-frontend:version2.0"

					}
				}

			}
		}

          stage('Deploy to Kubernetes') {
               steps {
                    script {
                         dir('SPE Major Project'){
                              withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'k8ss', namespace: '', restrictKubeConfigAccess: false, serverUrl: '') {
                                   sh 'kubectl apply -f deployment.yml --validate=false'
                                   sh 'kubectl apply -f service.yml --validate=false'
                              }
                         }
                    }
               }
          }
    }

}
